### ISSUE TITLE
Join pseudo headers into existing headers

### ISSUE THREAD

**Issue by williamle92** [tomMoulard/htransformation#36]
Hello, 

Is it possible to join pseudo headers (such as `:path`) into a newly created header?

My use-case:
I am trying to implement a rate limit per path using the `RateLimit` middleware with source criterion pointed to a new header. This new header will extract user id from cookie (which I was able to do), but I need to add the value of `:path` header to this new header to make it possible. 

Thank you for your time.

**Comment by williamle92** [comment]
Hello @tomMoulard ,

Pseudo-headers are sent in each request that give more details about the request. I believe `Traefik` sets these pseudo-headers on the request which become available on our flask request headers. 

Here are some examples of pseudo-headers taken from  [portswigger](https://portswigger.net/burp/documentation/desktop/http2/http2-basics-for-burp-users)
```
:method - The HTTP method of the request, such as GET or POST.
:path - The request path. Note that this includes the query string.
:authority - Roughly equivalent to the Host header in HTTP/1.
:scheme - The request scheme, typically http or https. Note that there is no equivalent in HTTP/1.
:status - The response status code.
```

Also an [example](https://i.stack.imgur.com/2F98q.png) you would see in google console.

**Comment by tomMoulard** [comment]
Here are all headers added by traefik:

```
X-Forwarded-For: 10.42.0.1
X-Forwarded-Host: localhost
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: traefik-5496cff6c7-4xwbh
```

It is not common for reverse proxy to add more headers that contain the request's data.

Nevertheless, if you are just trying to extract data from the cookies, you can find the cookies values as headers:

```
> curl localhost/whoami -H "Cookie: foo=bar"
...
GET /whoami HTTP/1.1
Host: localhost
User-Agent: curl/7.79.0-DEV
...
Cookie: foo=bar
```

**Comment by williamle92** [comment]
Thank you Tom for your response. So it seems like there are no ways for me to access these pseudo headers through traefik and it seems like it is not even supposed to be added as a regular header((I read some some pep). I will close this thread.
